language: android

android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-19

jdk:
  - oraclejdk8

cache:
    directories:
        - .nvm
        - node_modules

install:
    - nvm install 4
    - npm install ./nativescript.tgz --ignore-scripts

before_script:
    - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
    - echo no | android create avd --force -n test -t android-19 -b armeabi-v7a
    - emulator -avd test -no-audio -no-window &
    - android-wait-for-emulator

script:
    - pwd
    - ls -al node_modules/.bin
    - cd unit-test-proj
    - ../node_modules/.bin/tns usage-reporting disable
    - ../node_modules/.bin/tns error-reporting disable
    - ../node_modules/.bin/tns run android --justlaunch
    - ../node_modules/.bin/tns test android &
    - PID=$!
    - sleep 2m
    - kill -9 $PID
    - ../node_modules/.bin/tns device log &
    - PID=$!
    - ../node_modules/.bin/tns test android --justlaunch
    - kill -9 $PID
    - echo "Final"